# -*- coding: utf-8 -*-
"""
Small helper to load the plugin's icons directly from the ``icons`` folder
on disk, instead of going through a compiled Qt resource file
(resources.py, generated by pyrcc5 from resources.qrc).

pyrcc5-generated resource modules hard-import PyQt5, which is not
installed alongside QGIS 4 / Qt6, so the old ':/plugins/layout_panel/...'
resource paths can no longer be used. Loading icons straight from disk
works identically under Qt5 and Qt6, so it removes the need to keep the
.qrc file, resources.py and a build step in sync with the Qt version.
"""

import os

from qgis.PyQt.QtGui import QIcon

ICONS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'icons')


def icon(file_name):
    """Return a QIcon for a file in the plugin's icons/ folder.

    :param file_name: file name relative to the icons/ folder,
        e.g. 'mActionNewLayout.svg'
    :type file_name: str
    :rtype: QIcon
    """
    return QIcon(os.path.join(ICONS_DIR, file_name))
