# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayoutPanelDockWidget
                                 A QGIS plugin
 Add a panel to manage layouts without blocking the main interface
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-09
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Atelier JBP
        email                : jbpeter@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QAbstractItemView

from .modules.icons import icon
from .modules.project import Project
from .modules.layout_list import LayoutList
from .modules.layout_item import LayoutItem
from .modules.context_menu import ContextMenu
from .modules.template_menu import TemplateMenu
from .modules.map_extents import MapExtents

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'layout_panel_dockwidget_base.ui'))


class LayoutPanelDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    def __init__(self, iface, parent=None):
        """Initialize the layout panel"""
        super(LayoutPanelDockWidget, self).__init__(parent)

        self.setupUi(self)
        self.setObjectName("Layout Panel")
        self.iface = iface

        # Icons are loaded from disk (see modules/icons.py)
        self.pbCreateLayout.setIcon(icon('mActionNewLayout.svg'))
        self.tbTemplateMenu.setIcon(icon('mIconFolder.svg'))
        self.pbDeleteLayout.setIcon(icon('mActionDeleteSelected.svg'))

        # Initialize modules
        plugin_dir = os.path.dirname(os.path.realpath(__file__))
        self.project = Project(plugin_dir,parent=self)
        self.layout_list = LayoutList(parent=self)
        self.layout_item = LayoutItem(parent=self)
        self.context_menu = ContextMenu(parent=self)
        self.template_menu = TemplateMenu(parent=self)
        self.map_extents = MapExtents(parent=self)
        
        #Disable edit triggers - F2 shortcut to edit is managed by keyPressEvent
        self.listWidget.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        
        # Set connections        
        self.pbCreateLayout.clicked.connect(self.project.createNewLayout)
        self.pbDeleteLayout.clicked.connect(lambda: self.layout_list.removeSelectedLayouts(True))
        self.listWidget.itemDoubleClicked.connect(self.layout_item.openCurrentLayout)
        self.listWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.listWidget.customContextMenuRequested.connect(self.context_menu.openContextMenu)
        self.listWidget.itemDelegate().closeEditor.connect(self.layout_item.renameLayoutClosedEditor)
        self.mLineEdit.valueChanged.connect(self.layout_list.updateLayoutList)


    def keyPressEvent(self, event):
        """Keyboard shortcuts: F2 rename, Enter open, Delete remove
        (Shift+Delete without confirmation), Ctrl+D duplicate"""
        key = event.key()
        modifiers = event.modifiers()

        if key == Qt.Key.Key_F2:
            self.layout_item.renameLayout()
        elif key in (Qt.Key.Key_Enter, Qt.Key.Key_Return):
            self.layout_item.openCurrentLayout()
        elif key == Qt.Key.Key_Delete:
            ask_confirmation = not (modifiers & Qt.KeyboardModifier.ShiftModifier)
            self.layout_list.removeSelectedLayouts(ask_confirmation)
        elif key == Qt.Key.Key_D and modifiers & Qt.KeyboardModifier.ControlModifier:
            self.layout_list.duplicateSelectedLayouts()
        else:
            super().keyPressEvent(event)
            return
        event.accept()


    def cleanup(self):
        """Disconnect from QGIS signals and remove canvas items when the plugin is unloaded"""
        self.project.cleanup()
        self.layout_list.cleanup()
        self.map_extents.cleanup()
